### ISSUE TITLE
unable to initialize database

### ISSUE THREAD

**Issue by nityanantan23** [Tensor-Systems/tensoremr-server#2]
when i run `go rum main.go`

failed to initialize database, got error failed to connect to `host=localhost user=postgres database=emr`: failed SASL auth (FATAL: password authentication failed for user

**Comment by kidus-tiliksew** [comment]
You need to start a PostgreSQL database and create the database `emr`. To connect to the database, rename the `.env.example` file to `.env` and set the password to your database plus other configurations

**Comment by nityanantan23** [comment]
thanks, also how i seed data?

**Comment by kidus-tiliksew** [comment]
If you pulled the latest version, it automatically seeds some data for you. Check the `SeedData` function in `pkg/server/server.go`
